<a href="https://colab.research.google.com/github/RichardKameri/tydata/blob/main/numpyexe5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Example array
array = np.array([1, 3, 8, 10, 15])

# Given value
given_value = 9

# Find the index of the nearest value
index = (np.abs(array - given_value)).argmin()

# Get the nearest value
nearest_value = array[index]

# Display the result
print("Array:", array)
print("Given value:", given_value)
print("Nearest value:", nearest_value)


Array: [ 1  3  8 10 15]
Given value: 9
Nearest value: 8


In [2]:
import numpy as np

# Define the two arrays
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4], [5], [6]])

# Initialize an output array with the shape resulting from the broadcasting
result = np.zeros((3, 3))

# Create an iterator for the two arrays and the output array
with np.nditer([array1, array2, result], flags=['external_loop'], op_flags=[['readonly'], ['readonly'], ['writeonly']]) as it:
    for x, y, z in it:
        z[...] = x + y

# Display the result
print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Sum:\n", result)


Array 1:
 [[1 2 3]]
Array 2:
 [[4]
 [5]
 [6]]
Sum:
 [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [3]:
import numpy as np

class NamedArray(np.ndarray):
    def __new__(cls, input_array, name="default"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "default")

# Example usage
data = np.array([1, 2, 3, 4, 5])
named_array = NamedArray(data, name="MyArray")

print("Array:", named_array)
print("Name:", named_array.name)


Array: [1 2 3 4 5]
Name: MyArray


In [4]:
import numpy as np

# Example vector and index array
vector = np.array([0, 1, 2, 3, 4, 5])
indices = np.array([0, 1, 1, 2, 3, 3, 3])

# Add 1 to each element indexed by the second vector
np.add.at(vector, indices, 1)

# Display the modified vector
print("Modified Vector:", vector)


Modified Vector: [1 3 3 6 4 5]


In [5]:
import numpy as np

# Example vector X
X = np.array([1, 2, 3, 4, 5])

# Index list I
I = np.array([0, 1, 2, 1, 0])

# Initialize array F with zeros of appropriate size
F = np.zeros(3, dtype=int)

# Accumulate elements of X into F based on I
np.add.at(F, I, X)

# Display the result
print("Vector X:", X)
print("Index List I:", I)
print("Accumulated Array F:", F)


Vector X: [1 2 3 4 5]
Index List I: [0 1 2 1 0]
Accumulated Array F: [6 6 3]


In [6]:
import numpy as np

# Example image with random colors (assuming a small image for demonstration)
w, h = 4, 4
image = np.random.randint(0, 256, size=(w, h, 3), dtype=np.uint8)

# Reshape the image to combine the color channels
flat_image = image.reshape(-1, 3)

# Find unique colors
unique_colors = np.unique(flat_image, axis=0)

# Compute the number of unique colors
num_unique_colors = unique_colors.shape[0]

# Display the result
print("Number of unique colors:", num_unique_colors)


Number of unique colors: 16


In [7]:
import numpy as np

# Example 4D array
array_4d = np.random.rand(2, 3, 4, 5)

# Compute the sum over the last two axes
sum_over_axes = np.sum(array_4d, axis=(-2, -1))

# Display the result
print("Original Array Shape:", array_4d.shape)
print("Sum Over Last Two Axes:", sum_over_axes)
print("Result Shape:", sum_over_axes.shape)


Original Array Shape: (2, 3, 4, 5)
Sum Over Last Two Axes: [[8.49957242 9.64577375 8.98990103]
 [9.07735268 9.0871941  9.35081285]]
Result Shape: (2, 3)


In [8]:
import numpy as np

# Example vectors D and S
D = np.array([10, 20, 30, 40, 50])
S = np.array([0, 1, 0, 1, 0])

# Find unique subset indices
unique_indices = np.unique(S)

# Initialize an array to store the means
means = np.zeros(len(unique_indices))

# Calculate the mean for each subset
for idx in unique_indices:
    means[idx] = np.mean(D[S == idx])

# Display the results
print("Vector D:", D)
print("Subset Indices S:", S)
print("Means of Subsets:", means)


Vector D: [10 20 30 40 50]
Subset Indices S: [0 1 0 1 0]
Means of Subsets: [30. 30.]


In [9]:
import numpy as np

# Example matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Compute the diagonal of the dot product
diagonal = np.einsum('ij,ji->i', A, B)

# Display the result
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Diagonal of Dot Product:", diagonal)


Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
Diagonal of Dot Product: [30 69 90]


In [10]:
import numpy as np

# Original vector
original_vector = np.array([1, 2, 3, 4, 5])

# Size of the new vector: original length + (3 zeros * (original length - 1))
new_size = len(original_vector) + (3 * (len(original_vector) - 1))

# Initialize the new vector with zeros
new_vector = np.zeros(new_size, dtype=int)

# Assign values from the original vector to the new vector
new_vector[::4] = original_vector

# Display the new vector
print("Original Vector:", original_vector)
print("New Vector with Interleaved Zeros:", new_vector)


Original Vector: [1 2 3 4 5]
New Vector with Interleaved Zeros: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [11]:
import numpy as np

# Example arrays
array_3d = np.random.rand(5, 5, 3)
array_2d = np.random.rand(5, 5)

# Multiply the (5, 5, 3) array by the (5, 5) array using broadcasting
result = array_3d * array_2d[:, :, np.newaxis]

# Display the result
print("3D Array:\n", array_3d)
print("2D Array:\n", array_2d)
print("Result of Multiplication:\n", result)


3D Array:
 [[[0.69804836 0.4123853  0.34479555]
  [0.44473997 0.00899837 0.70472304]
  [0.68912482 0.83273806 0.62032144]
  [0.50217535 0.90248138 0.05317128]
  [0.37320426 0.38506145 0.93403949]]

 [[0.04312465 0.02790205 0.98527939]
  [0.30650665 0.91365604 0.26457484]
  [0.55501227 0.36726134 0.50422558]
  [0.56373585 0.91085702 0.57724541]
  [0.35593816 0.22453301 0.64373857]]

 [[0.87882925 0.21877372 0.71276527]
  [0.05046747 0.75864665 0.94580286]
  [0.99754681 0.57502019 0.91000456]
  [0.6470312  0.43064384 0.80059181]
  [0.61105042 0.67010069 0.88996147]]

 [[0.02453589 0.0085851  0.80721289]
  [0.41937825 0.39660681 0.9342317 ]
  [0.42274412 0.45098167 0.96894045]
  [0.17079373 0.92004675 0.93307875]
  [0.41146449 0.95344743 0.9460692 ]]

 [[0.08454509 0.85423723 0.6517501 ]
  [0.40146276 0.31101832 0.28883379]
  [0.88143094 0.28907717 0.40587366]
  [0.70471659 0.37236531 0.61798607]
  [0.7293896  0.60943409 0.46600792]]]
2D Array:
 [[0.73563492 0.17611355 0.98447621 0.728844

In [12]:
import numpy as np

# Example array
array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

# Indices of the rows you want to swap
row1, row2 = 0, 2

# Swap the rows
array[[row1, row2]] = array[[row2, row1]]

# Display the result
print("Array after swapping rows {} and {}:\n{}".format(row1, row2, array))


Array after swapping rows 0 and 2:
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [13]:
import numpy as np

# Example set of 10 triplets (triangles with shared vertices)
triangles = np.array([
    [0, 1, 2],
    [2, 3, 4],
    [4, 5, 6],
    [6, 7, 8],
    [8, 9, 0],
    [0, 2, 4],
    [4, 6, 8],
    [8, 0, 2],
    [2, 4, 6],
    [6, 8, 0]
])

# Function to get unique line segments
def get_unique_segments(triangles):
    segments = set()
    for triangle in triangles:
        for i in range(3):
            # Create a sorted tuple for each edge to avoid duplicates
            edge = tuple(sorted([triangle[i], triangle[(i + 1) % 3]]))
            segments.add(edge)
    return segments

# Find the unique line segments
unique_segments = get_unique_segments(triangles)

# Display the unique line segments
print("Unique Line Segments:", unique_segments)


Unique Line Segments: {(3, 4), (4, 6), (0, 2), (8, 9), (0, 8), (2, 8), (6, 8), (4, 5), (5, 6), (4, 8), (0, 1), (2, 4), (1, 2), (0, 4), (6, 7), (0, 9), (0, 6), (2, 3), (2, 6), (7, 8)}


In [14]:
import numpy as np

# Given sorted array C corresponding to a bincount
C = np.array([3, 2, 1, 4])

# Initialize an empty list to hold the result
A = []

# Populate the result array
for value, count in enumerate(C):
    A.extend([value] * count)

# Convert the result list to a NumPy array
A = np.array(A)

# Display the result
print("Array A:", A)
print("np.bincount(A):", np.bincount(A))
print("C:", C)


Array A: [0 0 0 1 1 2 3 3 3 3]
np.bincount(A): [3 2 1 4]
C: [3 2 1 4]


In [15]:
import numpy as np

# Example array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the window size
window_size = 3

# Compute the sliding window averages
averages = np.convolve(array, np.ones(window_size)/window_size, mode='valid')

# Display the result
print("Array:", array)
print("Sliding Window Averages:", averages)


Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding Window Averages: [2. 3. 4. 5. 6. 7. 8. 9.]


In [16]:
import numpy as np

# Example array
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define the window size
window_size = 3

# Compute the sliding window averages
averages = np.convolve(array, np.ones(window_size)/window_size, mode='valid')

# Display the result
print("Array:", array)
print("Sliding Window Averages:", averages)


Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding Window Averages: [2. 3. 4. 5. 6. 7. 8. 9.]


In [17]:
import numpy as np

# Example one-dimensional array Z
Z = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Define the window size
window_size = 3

# Use a list comprehension to create the 2D array with shifted rows
two_d_array = np.array([Z[i:i+window_size] for i in range(len(Z) - window_size + 1)])

# Display the result
print("Original Array Z:", Z)
print("Two-dimensional Array:\n", two_d_array)


Original Array Z: [0 1 2 3 4 5 6 7 8 9]
Two-dimensional Array:
 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [18]:
import numpy as np

# Example boolean array
bool_array = np.array([True, False, True, False])

# Negate the boolean array in place
bool_array = ~bool_array

# Display the result
print("Negated Boolean Array:", bool_array)


Negated Boolean Array: [False  True False  True]


In [19]:
import numpy as np

# Example 1D array X
X = np.array([10, 20, 30, 40, 50])

# Number of bootstrap samples
N = 10000

# Function to compute bootstrap samples
def bootstrap_means(X, N):
    boot_means = np.empty(N)
    for i in range(N):
        sample = np.random.choice(X, size=len(X), replace=True)
        boot_means[i] = np.mean(sample)
    return boot_means

# Compute bootstrap means
boot_means = bootstrap_means(X, N)

# Compute the 95% confidence interval
lower_bound = np.percentile(boot_means, 2.5)
upper_bound = np.percentile(boot_means, 97.5)

# Display the result
print("Bootstrapped 95% Confidence Interval for the Mean:", (lower_bound, upper_bound))


Bootstrapped 95% Confidence Interval for the Mean: (18.0, 42.0)
