<a href="https://colab.research.google.com/github/RichardKameri/tydata/blob/main/numpyexe1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

CREATING A NULL VECTOR OF SIZE 10

In [2]:
import numpy as np
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


HOW TO FIND THE MEMORY SIZE OF AN ARRAY

In [3]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
memory_size = array.nbytes
print(memory_size)

40


HOW TO GET THE  DOCUMENTATION OF THE NUMPY ADD FUNCTION FROM THE COMMAND LINE

In [4]:
import numpy as np
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

CREATING A NULL VECTOR OF SIZE 10 BUT THE FIFTH VALUE WHICH IS 1


In [5]:
import numpy as np
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


CREATE A VECTOR WITH VALUES RANGING FROM 10 TO 49


In [6]:
import numpy as np
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


REVERSE A VECTOR ( FIRST ELEMENT BECOMES LAST)

In [7]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5])
reversed_vector = vector[::-1]
print(reversed_vector)

[5 4 3 2 1]


CREATE A 3*3 MATRIX WITH VALUE RANGING FROM 0 TO 8

In [8]:
import numpy as np
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


FIND INDICES OF NON ZERO ELEMENTS FROM[1,2,0,0,4,0]

In [9]:
import numpy as np
array = np.array([1, 2, 0, 0, 4, 0])
indices = np.nonzero(array)
print(indices)

(array([0, 1, 4]),)


  CREATE A 3*3 IDENTITY MATRIX

In [10]:
import numpy as np
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


CREATE A 3*3*3 ARRAY WITH RANDOM VALUES

In [11]:
import numpy as np
array = np.random.rand(3, 3, 3)
print(array)

[[[0.88318134 0.37236606 0.67709963]
  [0.57209708 0.2547891  0.28216962]
  [0.8742795  0.1206593  0.80438461]]

 [[0.84279168 0.19108203 0.77480556]
  [0.93217148 0.12316123 0.29683922]
  [0.43168401 0.93315453 0.84408659]]

 [[0.75222594 0.5005331  0.42060357]
  [0.0513288  0.8725216  0.91686609]
  [0.64962314 0.48564223 0.5237032 ]]]


CREATE A 10*10 ARRAY WITH RANDOM VALUES AND FIND THE MAXIMUM AND MINIMUM VALUES

In [14]:
import numpy as np
array = np.random.rand(10, 10)
min_value = np.min(array)
max_value = np.max(array)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

Minimum value: 0.008649716737503588
Maximum value: 0.993618678712122


CREATE A RANDOM VECTOR OF SIZE 30 AND FIND THE MEAN VALUE

In [15]:
import numpy as np
vector = np.random.rand(30)
mean_value = np.mean(vector)
print("Mean value:", mean_value)

Mean value: 0.43396163825081013


CREATE A 2D ARRAY  WITH 1 ON THE BORDER AND 0 INSIDE

In [16]:
import numpy as np
array = np.ones((5, 5))
array[1:-1, 1:-1] = 0
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
