<a href="https://colab.research.google.com/github/RichardKameri/tydata/blob/main/numpyexe3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Ignore all NumPy warnings
np.seterr(all='ignore')

# Example operation that would normally generate a warning
result = np.array([1.0, 2.0, 0.0]) / np.array([0.0, 0.0, 0.0])
print("Result:", result)

# Reset to default behavior (optional but recommended after the critical section)
np.seterr(all='warn')


Result: [inf inf nan]


{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

In [2]:
import numpy as np
result_standard = np.sqrt(-1)
print(result_standard)


nan


<ipython-input-2-b4fb279bd3bc>:2: RuntimeWarning: invalid value encountered in sqrt
  result_standard = np.sqrt(-1)


In [3]:
import numpy as np
result_emath = np.emath.sqrt(-1)
print(result_emath)


1j


In [4]:
comparison_result = np.sqrt(-1) == np.emath.sqrt(-1)
print(comparison_result)


False


<ipython-input-4-593bf5f14177>:1: RuntimeWarning: invalid value encountered in sqrt
  comparison_result = np.sqrt(-1) == np.emath.sqrt(-1)


In [5]:
from datetime import datetime, timedelta

# Get today's date
today = datetime.now()

# Calculate yesterday's date
yesterday = today - timedelta(days=1)

# Calculate tomorrow's date
tomorrow = today + timedelta(days=1)

# Print the dates
print("Yesterday:", yesterday.strftime('%Y-%m-%d'))
print("Today:", today.strftime('%Y-%m-%d'))
print("Tomorrow:", tomorrow.strftime('%Y-%m-%d'))


Yesterday: 2024-11-14
Today: 2024-11-15
Tomorrow: 2024-11-16


In [6]:
from datetime import datetime, timedelta

# Start date: July 1, 2016
start_date = datetime(2016, 7, 1)

# List to hold all the dates
july_dates = []

# Loop through the days of July 2016
for i in range(31):
    day = start_date + timedelta(days=i)
    july_dates.append(day.strftime('%Y-%m-%d'))

# Display all the dates
print(july_dates)


['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04', '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08', '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12', '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16', '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20', '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24', '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28', '2016-07-29', '2016-07-30', '2016-07-31']


In [7]:
import numpy as np

# Define example arrays A and B
A = np.array([1.0, 2.0, 3.0])
B = np.array([4.0, 5.0, 6.0])

# Compute A + B and store the result in A
A += B

# Compute -A/2 in place
A *= -0.5

# Display the result
print(A)


[-2.5 -3.5 -4.5]


In [8]:
import numpy as np

# Generate a random array of positive numbers
random_array = np.random.rand(5) * 10  # Scale to get numbers between 0 and 10

# Extract the integer part using np.floor
int_part_floor = np.floor(random_array)

print("Original Array:", random_array)
print("Integer Part using np.floor:", int_part_floor)


Original Array: [7.7148913  1.1165244  7.93698135 5.51391447 6.19610068]
Integer Part using np.floor: [7. 1. 7. 5. 6.]


In [9]:
# Extract the integer part using np.trunc
int_part_trunc = np.trunc(random_array)

print("Integer Part using np.trunc:", int_part_trunc)


Integer Part using np.trunc: [7. 1. 7. 5. 6.]


In [10]:
# Extract the integer part using astype(int)
int_part_astype = random_array.astype(int)

print("Integer Part using astype(int):", int_part_astype)


Integer Part using astype(int): [7 1 7 5 6]


In [11]:
# Extract the integer part using np.fix
int_part_fix = np.fix(random_array)

print("Integer Part using np.fix:", int_part_fix)


Integer Part using np.fix: [7. 1. 7. 5. 6.]


In [12]:
import numpy as np

# Create a 5x5 matrix with row values ranging from 0 to 4
matrix = np.tile(np.arange(5), (5, 1))

# Display the matrix
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [13]:
def generate_integers():
    for i in range(10):
        yield i


In [14]:
import numpy as np

# Use the generator function to create an array
gen = generate_integers()
array = np.fromiter(gen, dtype=int)

# Display the array
print("Generated Array:", array)


Generated Array: [0 1 2 3 4 5 6 7 8 9]


In [15]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)

# Display the vectors
print("Random Vector:", random_vector)
print("Sorted Vector:", sorted_vector)


Random Vector: [0.97971926 0.57433192 0.22677034 0.14537964 0.67280993 0.17504259
 0.52562152 0.47795646 0.29968576 0.19867809]
Sorted Vector: [0.14537964 0.17504259 0.19867809 0.22677034 0.29968576 0.47795646
 0.52562152 0.57433192 0.67280993 0.97971926]


In [16]:
import numpy as np

# Example small array
array = np.array([1, 2, 3, 4, 5])

# Using Python's built-in sum
result = sum(array)

print("Sum using Python's built-in sum:", result)


Sum using Python's built-in sum: 15


In [17]:
import numpy as np

# Generate two random arrays
A = np.random.rand(5)
B = np.random.rand(5)

# Check if the arrays are equal
are_equal = np.array_equal(A, B)

# Display the arrays and the result
print("Array A:", A)
print("Array B:", B)
print("Are arrays A and B equal?", are_equal)


Array A: [0.63778605 0.03326335 0.82968017 0.66267649 0.50308788]
Array B: [0.26941647 0.35320875 0.59090798 0.56661911 0.15977334]
Are arrays A and B equal? False


In [18]:
import numpy as np

# Create a random array
array = np.random.rand(5)

# Make the array immutable (read-only)
array.flags.writeable = False

# Display the array
print("Immutable Array:", array)

# Attempt to modify the array (this will raise an error)
try:
    array[0] = 10
except ValueError as e:
    print("Error:", e)


Immutable Array: [0.49851511 0.09534504 0.39952552 0.03893548 0.82106193]
Error: assignment destination is read-only


In [19]:
import numpy as np

# Generate a random 10x2 matrix representing Cartesian coordinates
cartesian_coords = np.random.rand(10, 2)

# Split the matrix into x and y coordinates
x_coords = cartesian_coords[:, 0]
y_coords = cartesian_coords[:, 1]

# Calculate the radius r
r = np.sqrt(x_coords**2 + y_coords**2)

# Calculate the angle theta
theta = np.arctan2(y_coords, x_coords)

# Combine r and theta into a single matrix
polar_coords = np.column_stack((r, theta))

# Display the results
print("Cartesian Coordinates:\n", cartesian_coords)
print("Polar Coordinates (r, theta):\n", polar_coords)


Cartesian Coordinates:
 [[0.5142002  0.1313223 ]
 [0.25770405 0.90147083]
 [0.99154066 0.1011579 ]
 [0.28513267 0.05513269]
 [0.68880817 0.58469057]
 [0.2929823  0.0388592 ]
 [0.88944309 0.98563073]
 [0.84428339 0.46382531]
 [0.90381013 0.64208755]
 [0.67629373 0.10595757]]
Polar Coordinates (r, theta):
 [[0.53070462 0.25004644]
 [0.93758254 1.29235211]
 [0.99668741 0.10166917]
 [0.29041393 0.19100097]
 [0.90350416 0.70382247]
 [0.29554808 0.13186362]
 [1.32762078 0.8366513 ]
 [0.96330076 0.50236062]
 [1.10867001 0.6176871 ]
 [0.6845438  0.1554105 ]]


In [20]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Display the original vector
print("Original Vector:", random_vector)

# Find the index of the maximum value
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

# Display the modified vector
print("Modified Vector:", random_vector)


Original Vector: [0.93563366 0.9054732  0.21537992 0.36994055 0.54119119 0.79190208
 0.67447668 0.67121098 0.66034369 0.41380032]
Modified Vector: [0.         0.9054732  0.21537992 0.36994055 0.54119119 0.79190208
 0.67447668 0.67121098 0.66034369 0.41380032]
