<a href="https://colab.research.google.com/github/RichardKameri/tydata/blob/main/numpyexe2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

# Create an example array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Add a border filled with zeros around the array
bordered_array = np.pad(original_array, pad_width=1, mode='constant', constant_values=0)

print("Original Array:\n", original_array)
print("Array with Zero Border:\n", bordered_array)


Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array with Zero Border:
 [[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


0 * np.nan

Result: nan

Explanation: Multiplying zero by NaN (Not a Number) results in NaN.

np.nan == np.nan

Result: False

Explanation: NaN is not equal to anything, including itself. This is defined by the IEEE floating-point standard.

np.inf > np.nan

Result: False

Explanation: NaN is not comparable with any other numerical value. Any comparison with NaN returns False.

np.nan - np.nan

Result: nan

Explanation: Any arithmetic operation involving NaN will result in NaN.

np.nan in set([np.nan])

Result: True

Explanation: NaN can be found in a set that contains NaN.

0.3 == 3 * 0.1

Result: False

Explanation: Due to floating-point precision issues, 0.3 is not exactly equal to 3 * 0.1 in binary representation.

In [3]:
import numpy as np

# Values to place below the diagonal
values = [1, 2, 3, 4]

# Create the matrix with the values below the diagonal
matrix = np.diag(values, k=-1)

# Display the matrix
print(matrix)


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [4]:
import numpy as np

# Initialize an 8x8 matrix with zeros
checkerboard = np.zeros((8, 8), dtype=int)

# Fill the matrix with a checkerboard pattern
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

# Display the matrix
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [5]:
import numpy as np

# Define a 2x2 checkerboard pattern
checkerboard_pattern = np.array([[0, 1],
                                 [1, 0]])

# Tile the pattern to create an 8x8 checkerboard
checkerboard = np.tile(checkerboard_pattern, (4, 4))

# Display the matrix
print(checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [6]:
import numpy as np

# Generate a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Normalize the matrix
normalized_matrix = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))

# Display the original and normalized matrices
print("Original Matrix:\n", random_matrix)
print("Normalized Matrix:\n", normalized_matrix)


Original Matrix:
 [[0.04208389 0.8911675  0.58005482 0.24743952 0.99923084]
 [0.57525989 0.0418622  0.47929935 0.19802684 0.87860106]
 [0.27777476 0.9821855  0.89350995 0.87423556 0.71284512]
 [0.03334498 0.54510268 0.15166879 0.09451596 0.0231056 ]
 [0.650505   0.97746528 0.28691007 0.95686742 0.07534111]]
Normalized Matrix:
 [[0.01944248 0.88929357 0.57057148 0.22982084 1.        ]
 [0.56565927 0.01921536 0.46735166 0.17919958 0.87641978]
 [0.26089804 0.98253775 0.89169331 0.87194749 0.70660965]
 [0.01048982 0.53476445 0.13170768 0.07315697 0.        ]
 [0.64274478 0.97770208 0.27025678 0.95660043 0.05351312]]


In [8]:
import numpy as np

# Define a custom dtype for a color
color_dtype = np.dtype([
    ('red', np.uint8),
    ('green', np.uint8),
    ('blue', np.uint8),
    ('alpha', np.uint8)
])

# Create an array of colors using the custom dtype
colors = np.array([
    (255, 0, 0, 255),    # Red with full opacity
    (0, 255, 0, 255),    # Green with full opacity
    (0, 0, 255, 255),    # Blue with full opacity
    (255, 255, 0, 255)   # Yellow with full opacity
], dtype=color_dtype)

# Display the colors array
print(colors)


[(255,   0,   0, 255) (  0, 255,   0, 255) (  0,   0, 255, 255)
 (255, 255,   0, 255)]


In [9]:
import numpy as np

# Define a 5x3 matrix
matrix_a = np.random.rand(5, 3)

# Define a 3x2 matrix
matrix_b = np.random.rand(3, 2)

# Perform matrix multiplication
result_matrix = np.dot(matrix_a, matrix_b)

# Display the matrices
print("Matrix A (5x3):\n", matrix_a)
print("Matrix B (3x2):\n", matrix_b)
print("Resulting Matrix (5x2):\n", result_matrix)


Matrix A (5x3):
 [[0.23666957 0.21054564 0.00762706]
 [0.70139768 0.89367521 0.96624259]
 [0.39233666 0.75403031 0.29687031]
 [0.42280915 0.32604222 0.38619585]
 [0.14670448 0.52161731 0.14023832]]
Matrix B (3x2):
 [[0.37074531 0.14940261]
 [0.33896343 0.98971576]
 [0.66853078 0.51182771]]
Resulting Matrix (5x2):
 [[0.16421033 0.24764313]
 [1.20892602 1.48382481]
 [0.59951261 0.95683825]
 [0.52545471 0.58352365]
 [0.32495282 0.60994876]]


In [10]:
import numpy as np

# Example 1D array
array = np.array([1, 3, 5, 7, 9, 11])

# Negate all elements which are between 3 and 8
array[(array > 3) & (array < 8)] *= -1

# Display the updated array
print(array)


[ 1  3 -5 -7  9 11]


In [11]:
print(sum(range(5), -1))


9


In [12]:
from numpy import *
print(sum(range(5), -1))


10


Z**Z

Legal: This expression is legal. It performs element-wise exponentiation of Z by Z. For example, if Z = np.array([1, 2, 3]), the result would be array([1, 4, 27]).

2 << Z >> 2

Legal: This expression is legal. It performs bitwise left shift and then right shift operations. For example, if Z = np.array([1, 2, 3]), the result would be equivalent to shifting each element of 2 by Z positions to the left and then to the right by 2 positions.

Z <- Z

Illegal: This expression is not legal in NumPy as <- is not a valid operator. The correct expression for element-wise comparison would be something like Z < -Z.

1j*Z

Legal: This expression is legal. It performs element-wise multiplication of Z with the imaginary unit 1j, resulting in a complex array. For example, if Z = np.array([1, 2, 3]), the result would be array([0.+1.j, 0.+2.j, 0.+3.j]).

Z/1/1

Legal: This expression is legal. It divides Z by 1 twice, which essentially results in Z. For example, if Z = np.array([1, 2, 3]), the result would be array([1., 2., 3.]).

Z<Z>Z

Illegal: This expression is not legal in NumPy. Chained comparisons like Z < Z > Z are not supported in NumPy.

In [13]:
import numpy as np
result = np.array(0) / np.array(0)
print(result)  # nan


nan


<ipython-input-13-94ab483ecb4a>:2: RuntimeWarning: invalid value encountered in divide
  result = np.array(0) / np.array(0)


In [14]:
result = np.array(0) // np.array(0)
print(result)  # 0


0


<ipython-input-14-59d5546f9d55>:1: RuntimeWarning: divide by zero encountered in floor_divide
  result = np.array(0) // np.array(0)


In [15]:
result = np.array([np.nan]).astype(int).astype(float)
print(result)  # [-9.22337204e+18]


[-9.22337204e+18]


<ipython-input-15-796d3bbfe3f2>:1: RuntimeWarning: invalid value encountered in cast
  result = np.array([np.nan]).astype(int).astype(float)


In [16]:
import numpy as np

# Example float array
float_array = np.array([-2.3, -1.5, -0.2, 0.2, 1.5, 2.3])

# Function to round away from zero
def round_away_from_zero(array):
    return np.copysign(np.ceil(np.abs(array)), array)

# Apply the function to the float array
rounded_array = round_away_from_zero(float_array)

# Display the result
print("Original array:", float_array)
print("Rounded away from zero array:", rounded_array)


Original array: [-2.3 -1.5 -0.2  0.2  1.5  2.3]
Rounded away from zero array: [-3. -2. -1.  1.  2.  3.]


In [17]:
import numpy as np

# Define two example arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values
common_values = np.intersect1d(array1, array2)

# Display the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Common values:", common_values)


Array 1: [1 2 3 4 5]
Array 2: [4 5 6 7 8]
Common values: [4 5]
